### ISSUE TITLE
How to set Spark's driver-memory

### ISSUE THREAD

**Issue by cuihaikuo** [jaegertracing/jaeger-operator#798] opened 2019-11-28 03:41 UTC
## Requirement - what kind of business use case are you trying to solve?
```
$ kubectl logs jaeger-spark-dependencies-1574870100-4qxx9
19/11/27 15:55:39 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
19/11/27 15:55:47 ERROR SparkContext: Error initializing SparkContext.
java.lang.IllegalArgumentException: System memory 127729664 must be at least 471859200. Please increase heap size using the --driver-memory option or spark.driver.memory in Spark configuration.
```
I deployed a jaeger instance in k8s cluster with production strategy, there were some jaeger-spark-dependencies jobs excuted at 23:55 with above errors, how to set this driver-memory?

**Comment by pavolloffay** [comment] 2019-11-29 16:49
It seems that more users are facing this. We should include this in the main documentation and also document that dependencies job is optional.

Dependencies node embeds resources e.g.

```
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
```

**Comment by cuihaikuo** [comment] 2019-12-03 02:27
> It seems that more users are facing this. We should include this in the main documentation and also document that dependencies job is optional.
> 
> Dependencies node embeds resources e.g.
> 
> ```
>   resources:
>     requests:
>       memory: "64Mi"
>       cpu: "250m"
>     limits:
>       memory: "128Mi"
>       cpu: "500m"
> ```

I have tried to set limits memory to 512M, but still got the same error: `System memory 129761280 must be at least 471859200`, the different is that the value of `System memory` has changed.

**Comment by cuihaikuo** [comment] 2019-12-04 02:45
Finally, I set the limits memory to 2048M, problem solved.

**Comment by pavolloffay** [comment] 2019-12-04 09:42
Can you share how much data it processes in one go? For instance the number of stored dep links - this should be logged in the job.

**Comment by pavolloffay** [comment] 2019-12-04 14:55
This is duplicate of #745 

Feel free to continue commenting here or in the referenced issue. I am closing this.

**Closed by pavolloffay** 2019-12-04 14:55 UTC
Labels: documentation
