### ISSUE TITLE
During CRD reconciliation operator scales down replica set to 1 when HPA is enabled

### ISSUE THREAD

**Issue by rafalAtAdscale** [jaegertracing/jaeger-operator#963] opened 2020-03-16 01:58 UTC
Hi,

I've noticed that every time operator is restarted e.g.  pod is moved from one node to another it resets replicas to 1 ignoring current number of desired instances established by HPA. This behaviour (especially during peak time) is rather disruptive for our tracing pipeline and we'd like  for operator to not interfere with running HPA.

For example, the HPA is running 2 replicas
```
kubectl get hpa/jaeger-collector -n tracing                                                                                                  
NAME               REFERENCE                     TARGETS            MINPODS   MAXPODS   REPLICAS   AGE
jaeger-collector   Deployment/jaeger-collector   46%/90%, 20%/90%   2         24        2          12d 
```
When I deleted operator's pod, this happened:

```
kubectl get events --sort-by='.lastTimestamp' -ntracing
17s         Normal    ScalingReplicaSet   deployment/jaeger-collector                Scaled down replica set jaeger-collector-c5d59955d to 1
17s         Normal    Killing             pod/jaeger-collector-c5d59955d-j9t5x       Stopping container jaeger-collector
17s         Normal    SuccessfulDelete    replicaset/jaeger-collector-c5d59955d      Deleted pod: jaeger-collector-c5d59955d-j9t5x
15s         Normal    ScalingReplicaSet   deployment/jaeger-collector                Scaled up replica set jaeger-collector-c5d59955d to 2
15s         Normal    SuccessfulRescale   horizontalpodautoscaler/jaeger-collector   New size: 2; reason: Current number of replicas below Spec.MinReplicas
15s         Normal    Scheduled           pod/jaeger-collector-c5d59955d-hgvtq       Successfully assigned tracing/jaeger-collector-c5d59955d-hgvtq to ip-10-202-104-7.eu-central-1.compute.internal
15s         Normal    SuccessfulCreate    replicaset/jaeger-collector-c5d59955d      Created pod: jaeger-collector-c5d59955d-hgvtq
14s         Normal    Pulled              pod/jaeger-collector-c5d59955d-hgvtq       Container image "jaegertracing/jaeger-collector:1.17.0" already present on machine
13s         Normal    Started             pod/jaeger-collector-c5d59955d-hgvtq       Started container jaeger-collector
13s         Normal    Created             pod/jaeger-collector-c5d59955d-hgvtq       Created container jaeger-collector
```

**Comment by jpkrohling** [comment] 2020-03-16 12:56
> 17s         Normal    ScalingReplicaSet   deployment/jaeger-collector                Scaled down replica set jaeger-collector-c5d59955d to 1

Interesting. I thought I had seen this as well but I couldn't reproduce it again. Would you know why this happened? Are there any clues in the logs/events about it? I believe the operator will trigger a reconciliation whenever it is started, which might be the key to explain what's going on here if the operator is setting the `.Spec.Replicas` for the deployment to 1. Are you able to confirm that?

@kevinearls, @jkandasa perhaps one of you could also try to reproduce this?

**Comment by rafalAtAdscale** [comment] 2020-03-16 21:53
unfortunately i can't find antything interesting in operator's log. here's the logs from today, we had 4 replicas running, i restarted/deleted the operator and it scaled down HPA to 1 replica and than stabilized on 6 replicas.

```
time="2020-03-16T21:22:11Z" level=info msg=Versions arch=amd64 identity=tracing.jaeger-operator jaeger=1.17.0 jaeger-operator=v1.17.0 operator-sdk=v0.15.1 os=linux version=go1.13.3
time="2020-03-16T21:22:12Z" level=info msg="Auto-detected the platform" platform=kubernetes
time="2020-03-16T21:22:12Z" level=info msg="Automatically adjusted the 'es-provision' flag" es-provision=no
time="2020-03-16T21:22:12Z" level=info msg="Automatically adjusted the 'kafka-provision' flag" kafka-provision=no
time="2020-03-16T21:22:12Z" level=info msg="The service account running this operator does not have the role 'system:auth-delegator', consider granting it for additional capabilities"
time="2020-03-16T21:22:14Z" level=info msg="Install prometheus-operator in your cluster to create ServiceMonitor objects" error="no ServiceMonitor registered with the API"
time="2020-03-16T21:22:14Z" level=debug msg="Reconciling Jaeger" execution="2020-03-16 21:22:14.585691766 +0000 UTC" instance=jaeger namespace=tracing
time="2020-03-16T21:22:14Z" level=debug msg="Strategy chosen" instance=jaeger namespace=tracing strategy=production
time="2020-03-16T21:22:14Z" level=debug msg="Assembling the UI configmap" instance=jaeger namespace=tracing
time="2020-03-16T21:22:14Z" level=debug msg="Assembling the Sampling configmap" instance=jaeger namespace=tracing
time="2020-03-16T21:22:14Z" level=debug msg="assembling a collector deployment" instance=jaeger namespace=tracing
time="2020-03-16T21:22:14Z" level=debug msg="Assembling a query deployment" instance=jaeger namespace=tracing
time="2020-03-16T21:22:14Z" level=debug msg="injecting sidecar" deployment=jaeger-query instance=jaeger namespace=tracing
time="2020-03-16T21:22:14Z" level=debug msg="updating service account" account=jaeger instance=jaeger namespace=tracing
time="2020-03-16T21:22:14Z" level=debug msg="updating config maps" configMap=jaeger-ui-configuration instance=jaeger namespace=tracing
time="2020-03-16T21:22:14Z" level=debug msg="updating config maps" configMap=jaeger-sampling-configuration instance=jaeger namespace=tracing
time="2020-03-16T21:22:15Z" level=debug msg="updating cronjob" cronjob=jaeger-es-index-cleaner instance=jaeger namespace=tracing
time="2020-03-16T21:22:15Z" level=debug msg="updating daemonset" daemonset=jaeger-agent-daemonset instance=jaeger namespace=tracing
time="2020-03-16T21:22:15Z" level=debug msg="updating service" instance=jaeger namespace=tracing service=jaeger-collector-headless
time="2020-03-16T21:22:15Z" level=debug msg="updating service" instance=jaeger namespace=tracing service=jaeger-collector
time="2020-03-16T21:22:15Z" level=debug msg="updating service" instance=jaeger namespace=tracing service=jaeger-query
time="2020-03-16T21:22:15Z" level=debug msg="updating deployment" deployment=jaeger-collector instance=jaeger namespace=tracing
time="2020-03-16T21:22:15Z" level=debug msg="updating deployment" deployment=jaeger-query instance=jaeger namespace=tracing
time="2020-03-16T21:22:15Z" level=debug msg="Deployment has stabilized" desired=6 name=jaeger-collector namespace=tracing ready=6
time="2020-03-16T21:22:15Z" level=debug msg="Deployment has stabilized" desired=1 name=jaeger-query namespace=tracing ready=1
time="2020-03-16T21:22:15Z" level=debug msg="updating ingress" ingress=jaeger-query instance=jaeger namespace=tracing
time="2020-03-16T21:22:15Z" level=debug msg="updating hpa" hpa=jaeger-collector instance=jaeger namespace=tracing
time="2020-03-16T21:22:15Z" level=debug msg="Reconciling Jaeger completed" execution="2020-03-16 21:22:14.585691766 +0000 UTC" instance=jaeger namespace=tracing
```


for what it's worth, we're running jaeger in EKS `v1.14.9-eks-502bfb`

**Comment by rafalAtAdscale** [comment] 2020-03-17 00:53
i also confirmed today that any change to jaeger's CRD triggers the beahviour e.g. i changed agent config today and same thing happened

**Comment by jpkrohling** [comment] 2020-03-17 08:24
That's good info, @rafalAtAdscale! I think we have enough to do our own investigation. Of course, if you are able to help in preparing a PR fixing the problem, that would be greatly appreciated as well.

**Comment by jpkrohling** [comment] 2020-03-19 16:09
@rafalAtAdscale, I just sent a PR that should fix this problem. Would you be willing to try it out and confirm that it indeed fixes the problem you reported? I tried it locally here and could both reproduce the problem you said and confirm the fix works, but would be nice to get your confirmation as well.

You can use this image to try it out: `quay.io/jpkroehling/jaeger-operator:963-Deployment-back-to-1-replica`. In the first line of the operator's log, it should report this: `jaeger-operator=v1.17.1-4-gbe780294`.

**Comment by rafalAtAdscale** [comment] 2020-03-19 21:07
@jpkrohling your fix works on my end too. i deleted the operator to force restart and current state set by hpa was not altered on restart. thank you for very much for your help.  

```
20s         Normal    Killing                        pod/jaeger-operator-867c667c87-6g649       Stopping container jaeger-operator
20s         Normal    Scheduled                      pod/jaeger-operator-867c667c87-cc479       Successfully assigned tracing/jaeger-operator-867c667c87-cc479 to ip-10-202-106-49.eu-central-1.compute.internal
20s         Normal    SuccessfulCreate               replicaset/jaeger-operator-867c667c87      Created pod: jaeger-operator-867c667c87-cc479
19s         Normal    Pulling                        pod/jaeger-operator-867c667c87-cc479       Pulling image "quay.io/jpkroehling/jaeger-operator:963-Deployment-back-to-1-replica"
9s          Normal    Pulled                         pod/jaeger-operator-867c667c87-cc479       Successfully pulled image "quay.io/jpkroehling/jaeger-operator:963-Deployment-back-to-1-replica"
8s          Normal    Created                        pod/jaeger-operator-867c667c87-cc479       Created container jaeger-operator
7s          Normal    Started                        pod/jaeger-operator-867c667c87-cc479       Started container jaeger-operator
```

**Comment by jpkrohling** [comment] 2020-03-20 08:13
Thanks for the verification. The PR will be merged as soon as it's reviewed and will be made available in the next version.

**Closed** 2020-03-20 14:56 UTC
Labels: bug
