### ISSUE TITLE
documents are not up to date for installing operator

### ISSUE THREAD

**Issue by Snehil03** [jaegertracing/jaeger-operator#1927] opened 2022-06-01 13:16 UTC
https://www.jaegertracing.io/docs/1.35/operator/#installing-the-operator-on-kubernetes

document is not up to date as latest operator available is 1.34.1

**Comment by iblancasa** [comment] 2022-06-01 22:27
Actually the problem is the Jaeger documentation is generated independently of this repository. The documentation is hosted in [this repository](https://github.com/jaegertracing/documentation). When a new Jaeger release is done, the texts are updated and the URL to the Jaeger Operator manifest is modified.

Documentation is pointing to a Jaeger Operator manifest that was not created yet.

**Comment by iblancasa** [comment] 2022-06-07 13:50
I create an issue in the Jaeger documentation repository: https://github.com/jaegertracing/documentation/issues/580. @rubenvp8510, could you close this issue?

**Closed** 2022-06-21 19:23 UTC
Labels: bug
