### ISSUE TITLE
Makefiles needs a target for installing junitcli

### ISSUE THREAD

**Issue by kevinearls** [jaegertracing/jaeger-operator#1855] opened 2022-04-13 09:35 UTC
**Describe the bug**
make test uses the junitcli.  The Makefile should have a target to install this.

**To Reproduce**
1. make test

**Comment by kevinearls** [comment] 2022-04-13 09:38
I'm getting the following errors, even after installing junitcli and creating a reports directory

```
# Show a final report
junitcli --report reports
FATA[0000] no error suites found! No report printed
make: *** [run-e2e-tests] Error 1
```

The make test target should do whatever is required to run and report on tests

**Comment by frzifus** [comment] 2022-04-13 10:31
Its moved into the [hack folder](https://github.com/jaegertracing/jaeger-operator/blob/main/hack/run-e2e-tests.sh#L61) since https://github.com/jaegertracing/jaeger-operator/pull/1810.
try: `make tools`

**Comment by iblancasa** [comment] 2022-04-18 09:40
The problem is not produced in the `test` make target. It is in the `run-e2e-tests` make target. `junit` is installed as part of running `hack/run-e2e-tests.sh` (which is run for each test suite). It seems, for whatever reason, `Make` is not able to access that program from the path. I just created a PR fixing this issue.

**Comment by rubenvp8510** [comment] 2022-04-28 05:32
Is this already solved by https://github.com/jaegertracing/jaeger-operator/pull/1861 ? Can we close this issue?

**Comment by iblancasa** [comment] 2022-04-28 08:21
I think so @rubenvp8510

**Closed** 2022-05-11 17:13 UTC
Labels: bug
