### ISSUE TITLE
Jaeger Service not showing in Jaeger UI

### ISSUE THREAD

**Issue by Althea01** [jaegertracing/jaeger-operator#1106] opened 2020-06-26 19:19 UTC
I followed the documentation and can view the Jaeger UI according to this

NAME             CLASS    HOSTS   ADDRESS          PORTS   AGE
simplest-query   <none>   *       192.168.99.100   80      21h

But when I was compiling the code that exports traces to the Jaeger UI, I'm not seeing any traces.

Originally, I was setting up UI with docker run, and I haven't changed any code except that I'm now setting up UI with Kubernetes. Should I change the code where I export traces?

**Comment by jpkrohling** [comment] 2020-06-29 08:27
If you open the Jaeger UI and browse it a bit, do you see the traces from the "jaeger-query" service? If so, your Jaeger installation should be good to go. Is your application running in the same Kubernetes cluster? If so, it needs to have a sidecar with the Jaeger agent, or your Jaeger client (as part of your application) needs to be pointed to the jaeger-collector.

If your application is running outside of the Kubernetes cluster, you'll need to create some ingress objects exposing the collector. Note that this might potentially make your collector exposed to the internet, depending on your network configuration.

**Comment by Althea01** [comment] 2020-06-29 16:05
Yes, I can see the traces from the "jaeger-query" service. My application is currently running outside the Kubernetes cluster, and I have tried to expose the collector but I think I'm doing it in the wrong way, can you give me more insight on how to expose the collector?

**Comment by jpkrohling** [comment] 2020-07-02 09:36
This ingress is for the Jaeger Query (UI). You'll need an ingress for the Collector (14250), and then either point your agent to the collector (`--reporter.grpc.host-port`), assuming that you have an agent running close to your application.

**Comment by Althea01** [comment] 2020-07-10 17:27
I have my application running with kubernetes and agent injected as a sidecar with the application. I can see through logs that the services for jaeger query, collector and agent are running correctly but when I do kubectl get service jaeger-query I'm not able to see an external ip, is that related to ingress? Or is it related to me using allInOne Image.

**Comment by Althea01** [comment] 2020-07-10 20:08
I'm currently using the allInOne image and within my code, and both my application and my jaeger components run in the same namespace in my kubernetes cluster. Originally when I'm deploying the components locally, I'm setting the thriftEndpoint as "http://127.0.0.1:14268/api/traces" but now I think I need to change this? Also, I'm not able to see the external ip for the load balancer. Can someone offer me some help please?

**Comment by jpkrohling** [comment] 2020-07-13 13:20
If everything is inside a Kubernetes cluster, you might want to use the [Jaeger Operator](https://github.com/jaegertracing/jaeger-operator/) to provision a Jaeger instance, and deploy the [business-application-injected-sidecar.yaml](https://github.com/jaegertracing/jaeger-operator/blob/master/deploy/examples/business-application-injected-sidecar.yaml) example. Once you have that running, you can replicate that to your own business application.

**Comment by Althea01** [comment] 2020-07-13 16:02
So I don't need to change the thriftEndpoint?

**Comment by jpkrohling** [comment] 2020-07-14 07:27
>  I'm setting the thriftEndpoint as "http://127.0.0.1:14268/api/traces" but now I think I need to change this?

> So I don't need to change the thriftEndpoint?

Sorry, I should have been explicit here: yes, this is likely wrong.  If you are making your client send spans directly to the collector, it should be the collector's address, whatever that might be...

**Comment by jpkrohling** [comment] 2020-07-14 07:28
I'm closing this, as it looks like the problem is with your networking setup and client configuration. You can still ask questions, and feel free to reopen if you think you are hitting a bug somewhere.

**Closed by jpkrohling** 2020-07-14 07:28 UTC
Labels: needs-info

**Comment by Althea01** [comment] 2020-07-15 21:31
If I have a jaeger agent as a sidecar for an application in namespace A, and I have the jaeger collector in namespace B, is there something else I need to do to connect the two?

**Comment by jpkrohling** [comment] 2020-07-16 08:08
If pods from namespace A can talk to pods in namespace B, then all you need to do is configure your sidecar with the collector's hostname via `--reporter.grpc.host-port`... 

I'll suggest this one more, as it could help you with your next questions: you might want to use the [Jaeger Operator](https://github.com/jaegertracing/jaeger-operator/) to provision a Jaeger instance, and deploy the [business-application-injected-sidecar.yaml](https://github.com/jaegertracing/jaeger-operator/blob/master/deploy/examples/business-application-injected-sidecar.yaml) example. Once you have that running, you can replicate that to your own business application.
