### ISSUE TITLE
Create a new e2e test based for #670

### ISSUE THREAD

**Issue by kevinearls** [jaegertracing/jaeger-operator#675] opened 2019-09-26 15:06 UTC
Create a new e2e test that confirms #670 is fixed.  See https://github.com/jaegertracing/jaeger-operator/pull/672 for more information

**Comment by kevinearls** [comment] 2019-09-26 15:06
@jpkrohling  Can you assign this to me?  And maybe give it a better name?

**Comment by pavolloffay** [comment] 2022-03-21 16:13
Closing, the issue is not present right now.

**Closed by pavolloffay** 2022-03-21 16:13 UTC
Labels: qa
