### ISSUE TITLE
Jaeger agent as a DaemonSet

### ISSUE THREAD

**Issue by yoramda** [jaegertracing/jaeger-operator#1396] opened 2021-02-17 10:42 UTC
Hi,

My goal is to deploy jaeger operator to watch all k8s namespace on the cluster and set the strategy to production with elastic storage.

I am trying to configure jaeger agent as a DaemonSet,
Currently I am using strategy: allInOne and it is working ok, without sidecar
From the jaeger client I am pointing to the agent service host : simplest-agent.observability with udp port 6831 .
Here is the yaml file for strategy: allInOne:

apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simplest
spec:
  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:latest
    options:
      log-level: debug
  storage:
    type: memory 
    options:
      memory:
        max-traces: 100000
  #agent:
  #  strategy: DaemonSet 
  #  annotations:
  #    scheduler.alpha.kubernetes.io/critical-pod: ""

When trying to configure the agent as a DaemonSet it is not working , here is the yaml :

apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simplest
spec:
  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:latest
    options:
      log-level: debug
  storage:
    type: memory 
    options:
      memory:
        max-traces: 100000
  agent:
    strategy: DaemonSet 
    annotations:
      scheduler.alpha.kubernetes.io/critical-pod: ""

On my application deployment I have added 2 env variable :
My pod reside on other namespace then observability
env:	
	- name: JAEGER_AGENT_PORT
	  value: "6831"
	- name: JAEGER_AGENT_HOST
	  valueFrom:
		fieldRef:
		  fieldPath: status.hostIP

and from the client I have pointed the jaeger host and port from the JAEGER_AGENT_PORT & JAEGER_AGENT_HOST environment variable .
the problem is that it is not working ?

any ideas ?

Thanks in advanced .

**Comment by jpkrohling** [comment] 2021-02-17 11:19
How is your application creating the tracer? Is it using information from the env vars to build the tracer? Have you followed the troubleshooting guide?

https://www.jaegertracing.io/docs/1.21/troubleshooting/

**Comment by yoramda** [comment] 2021-02-17 13:46
My applocation is creating the trace from C# using openTelemtry nuget package,
that app is loading the env variable vars .
the troubleshooting guide did not helped .

Thanks again

**Comment by jpkrohling** [comment] 2021-02-18 09:59
>  the troubleshooting guide did not helped .

Could you please list the steps you followed and what you were able to determine? Could you get your application to print the traces to the logs, using the log reporter?

**Comment by yoramda** [comment] 2021-02-20 18:50
Hi,
i am starting to think that i may have a network access problem between my app deployment namespace and the observability namespace, i tried to setup the the role binding as it says at the Jaeger documentation 

https://www.jaegertracing.io/docs/1.21/operator/ :

"
When not using the cluster-wide resources (ClusterRole and ClusterRoleBinding), set the WATCH_NAMESPACE to the comma-separated list of namespaces that the Jaeger Operator should watch for events related to Jaeger resources. **It is possible to have the Jaeger Operator running in a given namespace (like, observability) and manage Jaeger resources in another (like, myproject). For that, use a RoleBinding like the following for each namespace the operator should watch for resources:**

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jaeger-operator-in-myproject
  namespace: myproject
subjects:
- kind: ServiceAccount
  name: jaeger-operator
  namespace: observability
roleRef:
  kind: Role
  name: jaeger-operator
  apiGroup: rbac.authorization.k8s.io
"

any ideas ?
Thanks in advanced

**Comment by yoramda** [comment] 2021-02-23 11:07
Hi,

Any Updates ? 

Thanks in advanced .

**Comment by jpkrohling** [comment] 2021-02-23 12:33
It's still very hard to understand your scenario. Are you able to reproduce it with a simple minikube cluster? If so, share all the steps you are taking. We have an e2e test for this case, perhaps it can help you figure out what you are missing?

https://github.com/jaegertracing/jaeger-operator/blob/b341e6a67487e74d76eb84daa933a468a7ec4461/test/e2e/examples1_test.go#L60-L84

**Comment by pavolloffay** [comment] 2022-02-02 10:27
Closing for missing user information.

Please re-open if the issue is still there.

**Closed by pavolloffay** 2022-02-02 10:27 UTC
Labels: needs-info
