### ISSUE TITLE
Use Cassandra as storage type but got collector CrashLoopBackOff

### ISSUE THREAD

**Issue by LuChenjing** [jaegertracing/jaeger-operator#1458] opened 2021-05-26 02:03 UTC
**Describe the bug**
Using Jaeger-operator to deploy Jaeger. Docker image  version is: jaeger-operator:1.22.1

**To Reproduce**
1. Here is my Jaeger spec yaml:
```bash
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: cassandra-with-create-schema
spec:
  strategy: production
  storage:
    type: cassandra
    options:
      cassandra:
        servers: simple-cluster-us-east-1-us-east-1a-0.scylla.svc
        keyspace: jaeger_v1_datacenter3
        username: cassandra
        password: cassandra
    cassandraCreateSchema:
      datacenter: "datacenter3"
      mode: "test"
```

And my Cassandra service
```bash
[root@node42 jaeger]# kubectl get svc -n scylla
NAME                                    TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                                                  AGE
simple-cluster-client                   ClusterIP   None           <none>        9180/TCP,5090/TCP                                        26d
simple-cluster-us-east-1-us-east-1a-0   ClusterIP   10.233.56.62   <none>        7000/TCP,7001/TCP,7199/TCP,10001/TCP,8000/TCP,9042/TCP   26d
```

2. After execute kubectl apply got this result:
```bash
[root@node42 jaeger]# kubectl get pods
NAME                                                      READY   STATUS             RESTARTS   AGE
cassandra-with-create-schema-cassandra-schema-job-b2dvl   0/1     Completed          0          27m
cassandra-with-create-schema-collector-77758cd6b7-5bsw4   0/1     CrashLoopBackOff   9          27m
cassandra-with-create-schema-query-694b9d8b89-7mczx       1/2     CrashLoopBackOff   9          27m

```
Services are just like:
```bash
[root@node42 jaeger]# kubectl get svc
NAME                                              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                                  AGE
cassandra-with-create-schema-collector            ClusterIP   10.233.24.49    <none>        9411/TCP,14250/TCP,14267/TCP,14268/TCP   33m
cassandra-with-create-schema-collector-headless   ClusterIP   None            <none>        9411/TCP,14250/TCP,14267/TCP,14268/TCP   33m
cassandra-with-create-schema-query                ClusterIP   10.233.24.148   <none>        16686/TCP                                33m
kubernetes                                        ClusterIP   10.233.0.1      <none>        443/TCP                                  161d
[root@node42 jaeger]#
```

Collector log is:
```bash
[root@node42 jaeger]# kubectl logs -f cassandra-with-create-schema-collector-77758cd6b7-5bsw4
2021/05/26 01:54:12 maxprocs: Leaving GOMAXPROCS=32: CPU quota undefined
{"level":"info","ts":1621994052.221555,"caller":"flags/service.go:117","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1621994052.221631,"caller":"flags/service.go:123","msg":"Mounting expvar handler on admin server","route":"/debug/vars"}
{"level":"info","ts":1621994052.2221916,"caller":"flags/admin.go:105","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1621994052.2222939,"caller":"flags/admin.go:111","msg":"Starting admin HTTP server","http-addr":":14269"}
{"level":"info","ts":1621994052.2223415,"caller":"flags/admin.go:97","msg":"Admin server started","http.host-port":"[::]:14269","health-status":"unavailable"}
[root@node42 jaeger]#
```
operator log is:
```bash 
time="2021-05-26T01:21:37Z" level=warning msg="Deployment has been removed." name=cassandra-with-create-schema-collector namespace=default
time="2021-05-26T01:21:37Z" level=error msg="failed to store the failed status into the current CustomResource after the reconciliation" error="Operation cannot be fulfilled on jaegers.jaegertracing.io \"cassandra-with-create-schema\": StorageError: invalid object, Code: 4, Key: /registry/jaegertracing.io/jaegers/default/cassandra-with-create-schema, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: a85f59c1-1084-445d-9bf6-b094e1e11655, UID in object meta: " execution="2021-05-26 01:20:25.967900047 +0000 UTC" instance=cassandra-with-create-schema namespace=default
time="2021-05-26T01:21:37Z" level=error msg="failed to apply the changes" error="deployment has been removed" execution="2021-05-26 01:20:25.967900047 +0000 UTC" instance=cassandra-with-create-schema namespace=default
time="2021-05-26T01:21:59Z" level=info msg="Cassandra port not specified. Using '9042' for the cassandra-create-schema job." instance=cassandra-with-create-schema namespace=default
time="2021-05-26T01:27:03Z" level=error msg="failed to apply the changes" error="timed out waiting for the condition" execution="2021-05-26 01:21:59.468616666 +0000 UTC" instance=cassandra-with-create-schema namespace=default
time="2021-05-26T01:27:04Z" level=info msg="Cassandra port not specified. Using '9042' for the cassandra-create-schema job." instance=cassandra-with-create-schema namespace=default
time="2021-05-26T01:32:04Z" level=error msg="failed to apply the changes" error="timed out waiting for the condition" execution="2021-05-26 01:27:04.577833382 +0000 UTC" instance=cassandra-with-create-schema namespace=default
time="2021-05-26T01:32:05Z" level=info msg="Cassandra port not specified. Using '9042' for the cassandra-create-schema job." instance=cassandra-with-create-schema namespace=default
time="2021-05-26T01:37:05Z" level=error msg="failed to apply the changes" error="timed out waiting for the condition" execution="2021-05-26 01:32:05.693763079 +0000 UTC" instance=cassandra-with-create-schema namespace=default
time="2021-05-26T01:37:06Z" level=info msg="Cassandra port not specified. Using '9042' for the cassandra-create-schema job." instance=cassandra-with-create-schema namespace=default
time="2021-05-26T01:42:06Z" level=error msg="failed to apply the changes" error="timed out waiting for the condition" execution="2021-05-26 01:37:06.79845696 +0000 UTC" instance=cassandra-with-create-schema namespace=default
time="2021-05-26T01:42:07Z" level=info msg="Cassandra port not specified. Using '9042' for the cassandra-create-schema job." instance=cassandra-with-create-schema namespace=default
time="2021-05-26T01:47:08Z" level=error msg="failed to apply the changes" error="timed out waiting for the condition" execution="2021-05-26 01:42:07.916547081 +0000 UTC" instance=cassandra-with-create-schema namespace=default
time="2021-05-26T01:47:09Z" level=info msg="Cassandra port not specified. Using '9042' for the cassandra-create-schema job." instance=cassandra-with-create-schema namespace=default
time="2021-05-26T01:52:09Z" level=error msg="failed to apply the changes" error="timed out waiting for the condition" execution="2021-05-26 01:47:09.027978284 +0000 UTC" instance=cassandra-with-create-schema namespace=default
time="2021-05-26T01:52:10Z" level=info msg="Cassandra port not specified. Using '9042' for the cassandra-create-schema job." instance=cassandra-with-create-schema namespace=default
time="2021-05-26T01:57:10Z" level=error msg="failed to apply the changes" error="timed out waiting for the condition" execution="2021-05-26 01:52:10.138864149 +0000 UTC" instance=cassandra-with-create-schema namespace=default
time="2021-05-26T01:57:11Z" level=info msg="Cassandra port not specified. Using '9042' for the cassandra-create-schema job." instance=cassandra-with-create-schema namespace=default
```

**Comment by LuChenjing** [comment] 2021-05-26 02:25
Update the describe info, seems cannot connect to the redinessProbe port
```bash
[root@node42 jaeger]# kubectl describe po cassandra-with-create-schema-5b4667bdd9-l24sn
Name:         cassandra-with-create-schema-5b4667bdd9-l24sn
Namespace:    default
Priority:     0
Node:         node41/10.144.210.41
Start Time:   Wed, 26 May 2021 10:17:48 +0800
Labels:       app=jaeger
              app.kubernetes.io/component=all-in-one
              app.kubernetes.io/instance=cassandra-with-create-schema
              app.kubernetes.io/managed-by=jaeger-operator
              app.kubernetes.io/name=cassandra-with-create-schema
              app.kubernetes.io/part-of=jaeger
              pod-template-hash=5b4667bdd9
Annotations:  linkerd.io/inject: disabled
              prometheus.io/port: 14269
              prometheus.io/scrape: true
              sidecar.istio.io/inject: false
Status:       Running
IP:           10.222.11.196
IPs:
  IP:           10.222.11.196
Controlled By:  ReplicaSet/cassandra-with-create-schema-5b4667bdd9
Containers:
  jaeger:
    Container ID:  docker://0f053a428fe677161e7c5b08a960d3dfae0c77aa7c7040b025b813bc97488afd
    Image:         jaegertracing/all-in-one:1.22.0
    Image ID:      docker-pullable://jaegertracing/all-in-one@sha256:ca6b733306168eae6257e6c5957c5f44ba406a3b0ae0d25074f1cf3a01f5ee8b
    Ports:         5775/UDP, 5778/TCP, 6831/UDP, 6832/UDP, 9411/TCP, 14267/TCP, 14268/TCP, 16686/TCP, 14269/TCP, 14250/TCP
    Host Ports:    0/UDP, 0/TCP, 0/UDP, 0/UDP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP
    Args:
      --cassandra.keyspace=jaeger_v1_datacenter3
      --cassandra.password=cassandra
      --cassandra.port=9042
      --cassandra.servers=simple-cluster-us-east-1-us-east-1a-0.scylla.svc
      --cassandra.username=cassandra
      --log-level=debug
      --sampling.strategies-file=/etc/jaeger/sampling/sampling.json
    State:          Running
      Started:      Wed, 26 May 2021 10:21:14 +0800
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Wed, 26 May 2021 10:19:28 +0800
      Finished:     Wed, 26 May 2021 10:21:14 +0800
    Ready:          False
    Restart Count:  2
    Liveness:       http-get http://:14269/ delay=5s timeout=1s period=15s #success=1 #failure=5
    Readiness:      http-get http://:14269/ delay=1s timeout=1s period=10s #success=1 #failure=3
    Environment:
      SPAN_STORAGE_TYPE:           cassandra
      COLLECTOR_ZIPKIN_HTTP_PORT:  9411
      JAEGER_DISABLED:             false
    Mounts:
      /etc/jaeger/sampling from cassandra-with-create-schema-sampling-configuration-volume (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from cassandra-with-create-schema-token-btssp (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  cassandra-with-create-schema-sampling-configuration-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      cassandra-with-create-schema-sampling-configuration
    Optional:  false
  cassandra-with-create-schema-token-btssp:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  cassandra-with-create-schema-token-btssp
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  <unknown>              default-scheduler  Successfully assigned default/cassandra-with-create-schema-5b4667bdd9-l24sn to node41
  Normal   Killing    3m2s                   kubelet, node41    Container jaeger failed liveness probe, will be restarted
  Normal   Pulled     2m32s (x2 over 4m11s)  kubelet, node41    Container image "jaegertracing/all-in-one:1.22.0" already present on machine
  Normal   Created    2m32s (x2 over 4m11s)  kubelet, node41    Created container jaeger
  Normal   Started    2m32s (x2 over 4m11s)  kubelet, node41    Started container jaeger
  Warning  Unhealthy  2m18s (x12 over 4m8s)  kubelet, node41    Readiness probe failed: HTTP probe failed with statuscode: 503
  Warning  Unhealthy  2m17s (x6 over 4m2s)   kubelet, node41    Liveness probe failed: HTTP probe failed with statuscode: 503
[root@node42 jaeger]#
```

**Comment by LuChenjing** [comment] 2021-05-26 08:54
I am able to connect the 14269 port of collector pod, but it cannot pass the livenessProbe/readinessProbe.

```bash
[root@node42 jaeger]# kubectl get pods -o wide
NAME                                                      READY   STATUS             RESTARTS   AGE    IP              NODE     NOMINATED NODE   READINESS GATES
cassandra-with-create-schema-cassandra-schema-job-5f76g   0/1     Completed          0          14m    10.222.11.232   node41   <none>           <none>
cassandra-with-create-schema-collector-847f9b8cd5-bk4mz   0/1     Running            7          14m    10.222.11.233   node41   <none>           <none>
cassandra-with-create-schema-query-6bd76cd8b-w6zlj        1/2     CrashLoopBackOff   6          14m    10.222.31.34    node42   <none>           <none>
ingress-controller-6445cffc44-zgf8d                       1/1     Running            0          7d1h   10.144.210.41   node41   <none>           <none>
[root@node42 jaeger]# telnet 10.222.11.233 14269
Trying 10.222.11.233...
Connected to 10.222.11.233.
Escape character is '^]'.
^C
Connection closed by foreign host.
[root@node42 jaeger]#
```

**Comment by jpkrohling** [comment] 2021-05-26 09:57
Could you share the logs from the query pod? Is your collector still crashing? Could you add "log-level=debug" to your options?

**Comment by jpkrohling** [comment] 2021-05-26 12:18
If you expose your Cassandra port with `kubectl port-forward`, are you able to get a local Jaeger connected to that instance? If you still have problems with a local Jaeger connecting to the remote Cassandra, how about a local Jaeger with a local container using the same image as your in-cluster Cassandra? Not sure it's a problem in the operator, based on the logs...

**Comment by LuChenjing** [comment] 2021-05-26 13:12
@jpkrohling Yes, the cassandra exposed by k8s service, and able to see the created keyspace in cassandra pod. 
Will update the result after trying the local Jaeger...

**Comment by LuChenjing** [comment] 2021-05-27 02:24
@jpkrohling Hello, did you mean "local jaeger" just use ```docker run```? I tried, and logs as below:
By checking the timestamp. Jaeger switched to success took more than 10 mins. ```1622080707.04903``` to ```1622081494.2027717```
So... maybe the time gap made the pods didn't pass the LivenessProbe/ReadinessProbe, then keep crashing?
```bash
[root@node42 ~]# docker run  -p 5775:5775/udp -p 6831:6831/udp -p 6832:6832/udp -p 5778:5778 -p 16686:16686 -p 14268:14268 -p 14250:14250 -e SPAN_STORAGE_TYPE=cassandra -e CASSANDRA_SERVERS=10.233.56.62 -e CASSANDRA_USERNAME=cassandra -e CASSANDRA_PASSWORD=cassandra -e CASSANDRA_KEYSPACE=jaeger_v1_datacenter3 jaegertracing/all-in-one:1.22.0
2021/05/27 01:58:27 maxprocs: Leaving GOMAXPROCS=32: CPU quota undefined
{"level":"info","ts":1622080707.0481822,"caller":"flags/service.go:117","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1622080707.0482547,"caller":"flags/service.go:123","msg":"Mounting expvar handler on admin server","route":"/debug/vars"}
{"level":"info","ts":1622080707.048814,"caller":"flags/admin.go:105","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1622080707.048988,"caller":"flags/admin.go:111","msg":"Starting admin HTTP server","http-addr":":14269"}
{"level":"info","ts":1622080707.04903,"caller":"flags/admin.go:97","msg":"Admin server started","http.host-port":"[::]:14269","health-status":"unavailable"}
{"level":"info","ts":1622081494.2027717,"caller":"cassandra/factory.go:105","msg":"Cassandra archive storage configuration is empty, skipping"}
{"level":"info","ts":1622081494.2631137,"caller":"server/grpc.go:76","msg":"Starting jaeger-collector gRPC server","grpc.host-port":":14250"}
{"level":"info","ts":1622081494.2632113,"caller":"server/http.go:47","msg":"Starting jaeger-collector HTTP server","http host-port":":14268"}
{"level":"info","ts":1622081494.2635596,"caller":"server/zipkin.go:48","msg":"Not listening for Zipkin HTTP traffic, port not configured"}
{"level":"info","ts":1622081494.2636569,"caller":"grpc/builder.go:70","msg":"Agent requested insecure grpc connection to collector(s)"}
{"level":"info","ts":1622081494.264042,"caller":"grpc@v1.29.1/clientconn.go:243","msg":"parsed scheme: \"\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1622081494.2640903,"caller":"grpc@v1.29.1/clientconn.go:249","msg":"scheme \"\" not registered, fallback to default scheme","system":"grpc","grpc_log":true}
{"level":"info","ts":1622081494.2641354,"caller":"grpc@v1.29.1/resolver_conn_wrapper.go:143","msg":"ccResolverWrapper: sending update to cc: {[{:14250  <nil> 0 <nil>}] <nil> <nil>}","system":"grpc","grpc_log":true}
{"level":"info","ts":1622081494.2641547,"caller":"grpc@v1.29.1/clientconn.go:667","msg":"ClientConn switching balancer to \"round_robin\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1622081494.264169,"caller":"grpc@v1.29.1/clientconn.go:682","msg":"Channel switches to new LB policy \"round_robin\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1622081494.2642233,"caller":"grpc@v1.29.1/clientconn.go:1056","msg":"Subchannel Connectivity change to CONNECTING","system":"grpc","grpc_log":true}
{"level":"info","ts":1622081494.2643187,"caller":"grpc@v1.29.1/clientconn.go:417","msg":"Channel Connectivity change to CONNECTING","system":"grpc","grpc_log":true}
{"level":"info","ts":1622081494.2643738,"caller":"grpc/builder.go:108","msg":"Checking connection to collector"}
{"level":"info","ts":1622081494.264476,"caller":"grpc/builder.go:119","msg":"Agent collector connection state change","dialTarget":":14250","status":"CONNECTING"}
{"level":"info","ts":1622081494.2644136,"caller":"grpc@v1.29.1/clientconn.go:1193","msg":"Subchannel picks a new address \":14250\" to connect","system":"grpc","grpc_log":true}
{"level":"info","ts":1622081494.2651544,"caller":"grpc@v1.29.1/clientconn.go:1056","msg":"Subchannel Connectivity change to READY","system":"grpc","grpc_log":true}
{"level":"info","ts":1622081494.2653089,"caller":"base/balancer.go:200","msg":"roundrobinPicker: newPicker called with info: {map[0xc0004fc740:{{:14250  <nil> 0 <nil>}}]}","system":"grpc","grpc_log":true}
{"level":"info","ts":1622081494.2653441,"caller":"grpc@v1.29.1/clientconn.go:417","msg":"Channel Connectivity change to READY","system":"grpc","grpc_log":true}
{"level":"info","ts":1622081494.2653658,"caller":"grpc/builder.go:119","msg":"Agent collector connection state change","dialTarget":":14250","status":"READY"}
{"level":"info","ts":1622081494.2656467,"caller":"command-line-arguments/main.go:218","msg":"Starting agent"}
{"level":"info","ts":1622081494.2657974,"caller":"querysvc/query_service.go:137","msg":"Archive storage not created","reason":"archive storage not configured"}
{"level":"info","ts":1622081494.2658167,"caller":"app/agent.go:69","msg":"Starting jaeger-agent HTTP server","http-port":5778}
{"level":"info","ts":1622081494.2658348,"caller":"app/flags.go:128","msg":"Archive storage not initialized"}
{"level":"info","ts":1622081494.2680593,"caller":"app/static_handler.go:181","msg":"UI config path not provided, config file will not be watched"}
{"level":"info","ts":1622081494.268779,"caller":"app/server.go:170","msg":"Query server started"}
{"level":"info","ts":1622081494.2688324,"caller":"healthcheck/handler.go:128","msg":"Health Check state change","status":"ready"}
{"level":"info","ts":1622081494.2688534,"caller":"app/server.go:230","msg":"Starting HTTP server","port":16686,"addr":":16686"}
{"level":"info","ts":1622081494.2688956,"caller":"app/server.go:249","msg":"Starting GRPC server","port":16685,"addr":":16685"}
```

![image](https://user-images.githubusercontent.com/42744697/119755753-171cb180-bed5-11eb-82c5-308939c9a35f.png)

**Comment by jpkrohling** [comment] 2021-05-27 08:12
This indeed looks like the cause. I just created a new issue on the main repo with your latest comment and will close this one here.

**Closed by jpkrohling** 2021-05-27 08:12 UTC
Labels: bug

**Comment by LuChenjing** [comment] 2021-06-03 10:16
@jpkrohling Hi, I just use a new Cassandra instance on another env which not abel to access the internet, So the image could not be pulled, may i ask how to specify the images use for each step?
Here is the jaeger manifest yaml file:
```bash
[root@fh-node2 jaeger]# cat test-jaeger.yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: cassandra-test
spec:
  strategy: production
  collector:
    image: registry.paas/onest-observer/jaeger-collector:1.22.0
    #replicas: 1
    options:
      log-level: debug
  agent:
    image: registry.paas/onest-observer/jaeger-agent:1.22.0
    options:
      log-level: debug
  query:
    image: registry.paas/onest-observer/jaeger-query:1.22.0
    options:
      log-level: debug
    #replicas: 1
  job:
    image: registry.paas/onest-observer/jaeger-cassandra-schema:1.22.0
  storage:
    type: cassandra

    options:
      cassandra:
        servers: 10.10.10.111
        keyspace: jaeger_v1_datacenter3
    cassandraCreateSchema:
      datacenter: "Beijing_data_center"
      mode: "prod"
[root@fh-node2 jaeger]#
```
And the create schema job pod log:
```bash
[root@fh-node2 jaeger]# kubectl get pods
NAME                                        READY   STATUS             RESTARTS   AGE
cassandra-test-cassandra-schema-job-jgr9l   0/1     ImagePullBackOff   0          6m59s
cassandra-test-cassandra-schema-job-sxp8x   0/1     ImagePullBackOff   0          99s
[root@fh-node2 jaeger]# kubectl describe po cassandra-test-cassandra-schema-job-jgr9l
Name:         cassandra-test-cassandra-schema-job-jgr9l
Namespace:    default
Priority:     0
Node:         fh-node1/
Start Time:   Thu, 03 Jun 2021 18:11:07 +0800
Labels:       controller-uid=d85d73e5-dcf3-42af-8f05-5ef6912a039f
              job-name=cassandra-test-cassandra-schema-job
Annotations:  k8s.v1.cni.cncf.io/network-status:
                [{
                    "name": "",
                    "ips": [
                        "10.222.37.203"
                    ],
                    "default": true,
                    "dns": {}
                }]
              k8s.v1.cni.cncf.io/networks-status:
                [{
                    "name": "",
                    "ips": [
                        "10.222.37.203"
                    ],
                    "default": true,
                    "dns": {}
                }]
              linkerd.io/inject: disabled
              prometheus.io/scrape: false
              sidecar.istio.io/inject: false
Status:       Failed
Reason:       DeadlineExceeded
Message:      Pod was active on the node longer than the specified deadline
IP:           10.222.37.203
IPs:
  IP:           10.222.37.203
Controlled By:  Job/cassandra-test-cassandra-schema-job
Containers:
  cassandra-test-cassandra-schema-job:
    Container ID:
    Image:          jaegertracing/jaeger-cassandra-schema:1.22.0
    Image ID:
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Environment:
      CQLSH_HOST:          10.10.10.111
      CQLSH_PORT:          9042
      MODE:                prod
      DATACENTER:          Beijing_data_center
      TRACE_TTL:           172800
      KEYSPACE:            jaeger_v1_datacenter3
      CASSANDRA_USERNAME:
      CASSANDRA_PASSWORD:
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-6qzlk (ro)
Volumes:
  default-token-6qzlk:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-6qzlk
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason          Age                        From               Message
  ----     ------          ----                       ----               -------
  Normal   Scheduled       7m9s                       default-scheduler  Successfully assigned default/cassandra-test-cassandra-schema-job-jgr9l to fh-node1
  Normal   AddedInterface  4m13s                      multus             Add eth0 [10.222.37.203/32]
  Warning  Failed          4m3s                       kubelet, fh-node1  Failed to pull image "jaegertracing/jaeger-cassandra-schema:1.22.0": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 114.114.114.114:53: read udp 100.71.0.236:20789->114.114.114.114:53: i/o timeout
  Warning  Failed          3m38s                      kubelet, fh-node1  Failed to pull image "jaegertracing/jaeger-cassandra-schema:1.22.0": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 114.114.114.114:53: read udp 100.71.0.236:47724->114.114.114.114:53: i/o timeout
  Warning  Failed          3m1s                       kubelet, fh-node1  Failed to pull image "jaegertracing/jaeger-cassandra-schema:1.22.0": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 114.114.114.114:53: read udp 100.71.0.236:27547->114.114.114.114:53: i/o timeout
  Normal   Pulling         2m6s (x4 over 4m13s)       kubelet, fh-node1  Pulling image "jaegertracing/jaeger-cassandra-schema:1.22.0"
  Warning  Failed          116s (x4 over 4m3s)        kubelet, fh-node1  Error: ErrImagePull
  Warning  Failed          116s                       kubelet, fh-node1  Failed to pull image "jaegertracing/jaeger-cassandra-schema:1.22.0": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 114.114.114.114:53: read udp 100.71.0.236:6160->114.114.114.114:53: i/o timeout
  Warning  Failed          102s (x6 over 4m2s)        kubelet, fh-node1  Error: ImagePullBackOff
  Normal   BackOff         <invalid> (x16 over 4m2s)  kubelet, fh-node1  Back-off pulling image "jaegertracing/jaeger-cassandra-schema:1.22.0"
[root@fh-node2 jaeger]#
```

**Comment by jpkrohling** [comment] 2021-06-03 10:22
You can specify the image in the same node that you configure the datacenter:

https://github.com/jaegertracing/jaeger-operator/blob/f7cee0596e4c9c3abddb6910b23673e2a5b5f939/pkg/apis/jaegertracing/v1/jaeger_types.go#L546-L550

```
  storage:
    type: cassandra

    options:
      cassandra:
        servers: 10.10.10.111
        keyspace: jaeger_v1_datacenter3
    cassandraCreateSchema:
      datacenter: "Beijing_data_center"
      image: your-image
```

**Comment by LuChenjing** [comment] 2021-06-04 07:20
@jpkrohling Thanks, I got it. 
Another question, I noticed that jaeger agent and jaeger query in one pod, how should I set the agent to daemonset instead of  deployment? I mean if I want to run the agent on node10~node20( nodes with special label), how to set the nodeSelector and makesure run each agent on each node?

**Comment by jpkrohling** [comment] 2021-06-04 08:10
Can't you use affinity and tolerations? 

https://github.com/jaegertracing/jaeger-operator/blob/f7cee0596e4c9c3abddb6910b23673e2a5b5f939/pkg/apis/jaegertracing/v1/jaeger_types.go#L218-L223

**Comment by LuChenjing** [comment] 2021-06-08 02:26
@jpkrohling Thanks, nodeAffinity meet my needs.
And update the info here, it takes fewer time after I switching another Cassandra(local deployed)..

However I met the same issue with [Multi-DC cassandra support](https://github.com/jaegertracing/jaeger/issues/2618), may I ask when the operator could support the param `replication_factor` of cassandra schema? Many thanks.
