### ISSUE TITLE
Sidecar injection - Do I need to restart deployment?

### ISSUE THREAD

**Issue by pzheng64** [jaegertracing/jaeger-operator#427] opened 2019-05-22 14:55 UTC
I'm working on creating customized version of Helm chart for deploying Jaeger operator and instance to my cluster.

When I do sidecar injection in the following order, the `jaeger` resources (jaeger-query, jaeger-collector, jaeger-agent) are not created.
- Existing deployment has already annotation `"sidecar.jaegertracing.io/inject": "jaeger"`
- Install Jaeger operator and an instance (name=jaeger) using Helm chart.
  https://github.com/helm/charts/tree/master/stable/jaeger-operator
- Create a Jaeger instance using all-in-one.yaml.

It does not create services in the target namespace of Jaeger instance. Should I switch to Jaeger DaemonSet for this purpose?

**Comment by objectiser** [comment] 2019-05-22 19:25
@pzheng64 I tried installing a Jaeger instance using the referenced helm chart with these steps:
```
minikube start --vm-driver kvm2 --memory 16384 --cpus 8
helm init
kubectl create ns observability
helm install stable/jaeger-operator --name jaeger --namespace observability
kubectl apply -f simplest.yaml 
```
where `simplest.yaml` is found [here](https://github.com/jaegertracing/jaeger-operator/blob/master/deploy/examples/simplest.yaml).
However the final step produced this error:
```
error: unable to recognize "deploy/examples/simplest.yaml": no matches for kind "Jaeger" in version "jaegertracing.io/v1"
```
Did you see this error? It would explain why the query, collector, etc are not being created?

If so, then you will need to create an issue against the helm chart.

In terms of ordering - I believe the sidecar injected agent would only occur if the operator was already installed before the app with the label was deployed. @jpkrohling can confirm.

**Comment by pzheng64** [comment] 2019-05-23 07:22
```
  apiVersion: jaegertracing.io/v1
  kind: Jaeger
  metadata:
    name: jaeger
  spec:
    strategy: allInOne
    allInOne:
      image: jaegertracing/all-in-one:latest
      options:
        log-level: debug
    storage:
      type: memory 
      options:
        memory:
          max-traces: 100000
    ingress:
      enabled: false
```
I have applyed the above YAML after installed Jaeger-operator, but I could not find the service `jaeger-query` and `jaeger-collector`.  It is said that all-in-one strategy is for running all the services inside single executable, but I don't quite get it.
Here is the custom ingress YAML I added for jaeger-query:
```
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: jaeger-query
    namespace: jx-staging # My namespace
  spec:
    rules:
    - host: jaeger-ui.k8.devfactory.com  # My domain for Jager UI
      http:
        paths:
        - path: /
          backend:
            serviceName: jaeger-query # Look here
            servicePort: 16686
```
Notice `serviceName: jaeger-query` here.  As I can't see the service `jaeger-query` running in my namespace, it does not show UI.

In a word, my question is:
- Does all-in-one strategy create services for jaeger-query and jaeger-collector?
- What is jaeger-zipkin used for?  I thought Zipkin is just an alternative for Jaeger, so confused about this.
- What can I do to re-inject into an existing deployment where sidecar injection was done before? As the deployment YAML definition shows `jaeger-agent` container inside it, I don't know how to remove it.

**Comment by objectiser** [comment] 2019-05-23 09:22
> Does all-in-one strategy create services for jaeger-query and jaeger-collector?

Yes - I deployed the jaeger operator using the instructions here, followed by your custom resource, and it correctly created the jaeger-query and jaeger-collector services.

> What is jaeger-zipkin used for? I thought Zipkin is just an alternative for Jaeger, so confused about this.

Jaeger provides a drop-in replacement for the zipkin server - so this port is used by clients that are reporting using the zipkin trace format.

> What can I do to re-inject into an existing deployment where sidecar injection was done before? As the deployment YAML definition shows jaeger-agent container inside it, I don't know how to remove it.

I think you will need to redeploy, then the new version of the deployment would be injected with an updated sidecar. (If that is what you are trying to do).

**Comment by jpkrohling** [comment] 2019-05-24 14:42
Perhaps we could change the operator to scan for annotated deployments on a first run?

**Comment by pzheng64** [comment] 2019-05-24 14:46
Could I get the updated version soon?

**Comment by jpkrohling** [comment] 2019-05-24 14:49
Sure, would you be willing to contribute a PR implementing this feature?

**Comment by pzheng64** [comment] 2019-05-24 14:49
@jpkrohling By the way, what could prevent creating services `jaeger-collector` and `jaeger-query` when we apply all-in-one YAML?

**Comment by jpkrohling** [comment] 2019-05-24 14:53
Are you consistently experiencing this behavior? Reading this issue, I have the impression that @objectiser could not reproduce your problem.

**Comment by pzheng64** [comment] 2019-05-24 14:55
@jpkrohling Yeah, it works fine at first a few times. But when I repeat removing applied resources, it does not work, not sure why.  Is there something similar to cache?  I had to repeat this as I was creating customized Helm chart for Jaeger tracing to use as sidecar.

**Comment by pzheng64** [comment] 2019-05-24 14:56
> Sure, would you be willing to contribute a PR implementing this feature?

I'm not well versed in the code structure of jaeger-operator.  I'm afraid I can not contribute.

**Comment by jpkrohling** [comment] 2019-05-24 15:04
> But when I repeat removing applied resources, it does not work, not sure why. Is there something similar to cache?

Not really, but you should either remove all the resources before stopping/removing the operator, or "change" the existing CR if you decide not to remove the resources. For instance:

```
# install and run the operator
kubectl apply -f operator.yaml -n observability

# create an instance named 'myjaeger'
kubectl apply -f myjaeger.yaml

# remove 'myjaeger'
kubectl delete jaeger myjaeger

# ensure all resources were removed
kubectl get pods

# stop/remove the operator
kubectl delete deployment jaeger-operator -n observability
```

If you don't remove the Jaeger CR, the operator might not be aware of its existence, as it won't trigger an event that is delivered by Kubernetes to the operator.

**Comment by objectiser** [comment] 2019-05-24 15:52
@jpkrohling 

> Perhaps we could change the operator to scan for annotated deployments on a first run?

This should also be considered in the context of  https://github.com/jaegertracing/jaeger-operator/issues/432, i.e. when new version of operator starts up, it should scan for existing jaeger instances and see whether their version needs to be updated.

**Comment by jpkrohling** [comment] 2019-05-28 12:06
I'm closing this, as the original question seems to be solved. I created #442, to address the situation where injection is desired but not yet performed.

**Closed** 2019-05-28 12:08 UTC
