### ISSUE TITLE
Jaeger not picking up k8s services.

### ISSUE THREAD

**Issue by Gauravjaitly** [jaegertracing/jaeger-operator#1358] opened 2021-01-07 22:11 UTC
Hi, i used this page to get jaeger for my k8s cluster. https://github.com/jaegertracing/jaeger-operator?utm_source=thenewstack&utm_medium=website&utm_campaign=platform
i am able to access the jaeger ui page but it doesnt gets my k8s services.

# kubectl logs -n observability deployment/jaeger-operator
```time="2021-01-07T06:48:47Z" level=info msg=Versions arch=amd64 identity=observability.jaeger-operator jaeger=1.21.0 jaeger-operator=v1.21.2 operator-sdk=v0.18.2 os=linux version=go1.14.12
time="2021-01-07T06:48:48Z" level=info msg="Consider running the operator in a cluster-wide scope for extra features"
time="2021-01-07T06:48:48Z" level=info msg="Auto-detected the platform" platform=kubernetes
time="2021-01-07T06:48:48Z" level=info msg="Auto-detected ingress api" ingress-api=networking
time="2021-01-07T06:48:48Z" level=info msg="Automatically adjusted the 'es-provision' flag" es-provision=no
time="2021-01-07T06:48:48Z" level=info msg="Automatically adjusted the 'kafka-provision' flag" kafka-provision=no
time="2021-01-07T06:48:50Z" level=info msg="Install prometheus-operator in your cluster to create ServiceMonitor objects" error="no ServiceMonitor registered with the API"
```

The Document says 
"You probably also want to download and customize the operator.yaml, setting the env var WATCH_NAMESPACE to have an empty value, so that it can watch for instances across all namespaces."
and that i dont know how to do. should i just leave the name: "empty" which has WATCH_NAMESPACE? if so, its throws error. 

if someone can tell how i can set it empty or how i can get my jaeger trace my k8s, that ll be very helpful.

**Comment by Gauravjaitly** [comment] 2021-01-08 05:51
Hey @jpkrohling can you help me with this please?

**Comment by jpkrohling** [comment] 2021-01-12 09:35
Closing as a duplicate of this thread in Gitter: https://gitter.im/jaegertracing/Lobby?at=5ff4e8c3e7f693041f523178

**Closed by jpkrohling** 2021-01-12 09:35 UTC
Labels: needs-triage
