### ISSUE TITLE
Pod is using wrong Service Account when using OAuth proxy

### ISSUE THREAD

**Issue by jwendell** [jaegertracing/jaeger-operator#478] opened 2019-06-24 15:57 UTC
When we use builtin feature of OAuth proxy, the whole pod gets the wrong serviceaccountName:
```yaml
      serviceAccount: jaeger-ui-proxy
      serviceAccountName: jaeger-ui-proxy
```

AFAIK this service account should be used only by the OAuth sidecar proxy: `- --openshift-service-account=jaeger-ui-proxy`

**Comment by jpkrohling** [comment] 2019-06-25 14:07
For completeness, here's a complete deployment object for the `simplest` example:

<details><summary>Expand</summary>
<p>

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    prometheus.io/port: "14269"
    prometheus.io/scrape: "true"
    sidecar.istio.io/inject: "false"
  creationTimestamp: 2019-06-25T13:43:19Z
  generation: 1
  labels:
    app: jaeger
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/instance: simplest
    app.kubernetes.io/managed-by: jaeger-operator
    app.kubernetes.io/name: simplest
    app.kubernetes.io/part-of: jaeger
  name: simplest
  namespace: myproject
  ownerReferences:
  - apiVersion: jaegertracing.io/v1
    controller: true
    kind: Jaeger
    name: simplest
    uid: 30ca11ef-974f-11e9-91b2-525400a3739d
  resourceVersion: "7904"
  selfLink: /apis/extensions/v1beta1/namespaces/myproject/deployments/simplest
  uid: 30efc56c-974f-11e9-91b2-525400a3739d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jaeger
      app.kubernetes.io/component: all-in-one
      app.kubernetes.io/instance: simplest
      app.kubernetes.io/managed-by: jaeger-operator
      app.kubernetes.io/name: simplest
      app.kubernetes.io/part-of: jaeger
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "14269"
        prometheus.io/scrape: "true"
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        app: jaeger
        app.kubernetes.io/component: all-in-one
        app.kubernetes.io/instance: simplest
        app.kubernetes.io/managed-by: jaeger-operator
        app.kubernetes.io/name: simplest
        app.kubernetes.io/part-of: jaeger
    spec:
      containers:
      - args:
        - --query.ui-config=/etc/config/ui.json
        - --sampling.strategies-file=/etc/jaeger/sampling/sampling.json
        env:
        - name: SPAN_STORAGE_TYPE
          value: memory
        - name: COLLECTOR_ZIPKIN_HTTP_PORT
          value: "9411"
        image: jaegertracing/all-in-one:1.12.0
        imagePullPolicy: IfNotPresent
        name: jaeger
        ports:
        - containerPort: 5775
          name: zk-compact-trft
          protocol: UDP
        - containerPort: 5778
          name: config-rest
          protocol: TCP
        - containerPort: 6831
          name: jg-compact-trft
          protocol: UDP
        - containerPort: 6832
          name: jg-binary-trft
          protocol: UDP
        - containerPort: 9411
          name: zipkin
          protocol: TCP
        - containerPort: 14267
          name: c-tchan-trft
          protocol: TCP
        - containerPort: 14268
          name: c-binary-trft
          protocol: TCP
        - containerPort: 16686
          name: query
          protocol: TCP
        - containerPort: 14269
          name: admin-http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 14269
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/config
          name: simplest-ui-configuration-volume
          readOnly: true
        - mountPath: /etc/jaeger/sampling
          name: simplest-sampling-configuration-volume
          readOnly: true
      - args:
        - --cookie-secret=SECRET
        - --https-address=:8443
        - --openshift-service-account=simplest-ui-proxy
        - --provider=openshift
        - --tls-cert=/etc/tls/private/tls.crt
        - --tls-key=/etc/tls/private/tls.key
        - --upstream=http://localhost:16686
        image: openshift/oauth-proxy:latest
        imagePullPolicy: Always
        name: oauth-proxy
        ports:
        - containerPort: 8443
          name: public
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/tls/private
          name: simplest-ui-oauth-proxy-tls
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: simplest-ui-proxy
      serviceAccountName: simplest-ui-proxy
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: ui
            path: ui.json
          name: simplest-ui-configuration
        name: simplest-ui-configuration-volume
      - configMap:
          defaultMode: 420
          items:
          - key: sampling
            path: sampling.json
          name: simplest-sampling-configuration
        name: simplest-sampling-configuration-volume
      - name: simplest-ui-oauth-proxy-tls
        secret:
          defaultMode: 420
          secretName: simplest-ui-oauth-proxy-tls
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-06-25T13:43:24Z
    lastUpdateTime: 2019-06-25T13:43:24Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2019-06-25T13:43:19Z
    lastUpdateTime: 2019-06-25T13:43:24Z
    message: ReplicaSet "simplest-589d4744bc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

```

</p>
</details>

Turns out, this is not a bug. The `jaeger-ui-proxy` service account is set with the appropriate options and we apply this only to the minimum components that need protection. In the case of the `all-in-one` deployments, it's the only deployment that exists, but for production/streaming strategies, the `jaeger-ui-proxy` service account is used only for the query deployment.

Here's the message we'd get if we were to use the regular service account for the all-in-one deployment: 

```
2019/06/25 13:57:54 oauthproxy.go:646: error redeeming code (client:172.17.0.1:49786): got 400 from "https://192.168.42.231:8443/oauth/token" {"error":"unauthorized_client","error_description":"The client is not authorized to request a token using this method."}
```

In the browser, all the user sees is a "500 Internal Error".

I'm now closing this issue, as I don't think we have a bug here.

**Closed by jpkrohling** 2019-06-25 14:07 UTC
Labels: bug

**Comment by jwendell** [comment] 2019-06-25 16:46
OK, my understand is that the pod would run with `jaeger` SA, and only the OAuth proxy container would run with `jaeger-ui-proxy` via the CLI flag `--openshift-service-account=jaeger-ui-proxy`.

**Comment by jpkrohling** [comment] 2019-06-26 05:06
That's what I thought too, but inspecting deeper, I found out that the current behavior is indeed correct.
