### ISSUE TITLE
e2e test failure in TestJaeger/jaeger-group/daemonset

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-operator#180] opened 2019-01-25 10:51 UTC
Started minikube (version: v0.32.0) using:
```
minikube start --vm-driver kvm2 --memory 16384 --cpus 4
```
Then ran `make test NAMESPACE=....`:
```
Running end-to-end tests...
time="2019-01-25T10:21:00Z" level=info msg="passing &{{Jaeger io.jaegertracing/v1alpha1} {with-cassandra  jaeger-jaeger-group-cassandra-1548411650    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {allInOne { {map[]} {[] [] map[] {map[] map[]}}} {0  {map[]} {[] [] map[] {map[] map[]}}} {0  {map[]} {[] [] map[] {map[] map[]}}} {0  {map[]} {[] [] map[] {map[] map[]}}} {  {map[]} {[] [] map[] {map[] map[]}}} {{[]}} {{[]}} {cassandra  {map[cassandra.servers:cassandra.default.svc cassandra.keyspace:jaeger_v1_datacenter1]} {<nil>  datacenter1 } {<nil>     false  false false false} {<nil> 0  }} {<nil>  {[] [] map[] {map[] map[]}}} {[] [] map[] {map[] map[]}}} {}}"
Forwarding from 127.0.0.1:16686 -> 16686
Forwarding from [::1]:16686 -> 16686
Forwarding from 127.0.0.1:14268 -> 14268
Forwarding from [::1]:14268 -> 14268

E0125 10:22:05.511875   11647 portforward.go:339] error closing listener: close tcp4 127.0.0.1:16686: use of closed network connection
E0125 10:22:05.512290   11647 portforward.go:339] error closing listener: close tcp6 [::1]:16686: use of closed network connection
E0125 10:22:05.513395   11647 portforward.go:339] error closing listener: close tcp4 127.0.0.1:14268: use of closed network connection
E0125 10:22:05.514483   11647 portforward.go:339] error closing listener: close tcp6 [::1]:14268: use of closed network connection
time="2019-01-25T10:24:36Z" level=info msg="passing &{{Jaeger io.jaegertracing/v1alpha1} {my-jaeger  jaeger-jaeger-group-my-jaeger-1548411870    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {allInOne { {map[log-level:debug memory.max-traces:10000]} {[] [] map[] {map[] map[]}}} {0  {map[]} {[] [] map[] {map[] map[]}}} {0  {map[]} {[] [] map[] {map[] map[]}}} {0  {map[]} {[] [] map[] {map[] map[]}}} {  {map[]} {[] [] map[] {map[] map[]}}} {{[]}} {{[]}} {  {map[]} {<nil>   } {<nil>     false  false false false} {<nil> 0  }} {<nil>  {[] [] map[] {map[] map[]}}} {[] [] map[] {map[] map[]}}} {}}"
time="2019-01-25T10:24:46Z" level=info msg="passing &{{Jaeger io.jaegertracing/v1alpha1} {my-jaeger  jaeger-jaeger-group-my-other-jaeger-1548411870    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {allInOne { {map[memory.max-traces:10000 log-level:debug]} {[] [] map[] {map[] map[]}}} {0  {map[]} {[] [] map[] {map[] map[]}}} {0  {map[]} {[] [] map[] {map[] map[]}}} {0  {map[]} {[] [] map[] {map[] map[]}}} {  {map[]} {[] [] map[] {map[] map[]}}} {{[]}} {{[]}} {  {map[]} {<nil>   } {<nil>     false  false false false} {<nil> 0  }} {<nil>  {[] [] map[] {map[] map[]}}} {[] [] map[] {map[] map[]}}} {}}"
Forwarding from 127.0.0.1:16686 -> 16686
Forwarding from [::1]:16686 -> 16686

Forwarding from 127.0.0.1:14268 -> 14268
Forwarding from [::1]:14268 -> 14268

E0125 10:25:16.291691   11647 portforward.go:339] error closing listener: close tcp4 127.0.0.1:14268: use of closed network connection
E0125 10:25:16.291712   11647 portforward.go:339] error closing listener: close tcp6 [::1]:14268: use of closed network connection
E0125 10:25:16.291691   11647 portforward.go:339] error closing listener: close tcp4 127.0.0.1:16686: use of closed network connection
E0125 10:25:16.293871   11647 portforward.go:339] error closing listener: close tcp6 [::1]:16686: use of closed network connection
--- FAIL: TestJaeger (451.27s)
    --- FAIL: TestJaeger/jaeger-group (401.00s)
        --- FAIL: TestJaeger/jaeger-group/daemonset (60.05s)
            client.go:57: resource type RoleBinding with namespace/name (jaeger-jaeger-group-daemonset-1548411469/jaeger-operator) created
            client.go:57: resource type Role with namespace/name (jaeger-jaeger-group-daemonset-1548411469/jaeger-operator) created
            client.go:57: resource type ServiceAccount with namespace/name (jaeger-jaeger-group-daemonset-1548411469/jaeger-operator) created
            client.go:57: resource type Deployment with namespace/name (jaeger-jaeger-group-daemonset-1548411469/jaeger-operator) created
            jaeger_test.go:60: Initialized cluster resources. Namespace: jaeger-jaeger-group-daemonset-1548411469
            wait_util.go:45: Waiting for full availability of jaeger-operator deployment (0/1)
            wait_util.go:45: Waiting for full availability of jaeger-operator deployment (0/1)
            wait_util.go:45: Waiting for full availability of jaeger-operator deployment (0/1)
            wait_util.go:45: Waiting for full availability of jaeger-operator deployment (0/1)
            wait_util.go:45: Waiting for full availability of jaeger-operator deployment (0/1)
            wait_util.go:45: Waiting for full availability of jaeger-operator deployment (0/1)
            wait_util.go:45: Waiting for full availability of jaeger-operator deployment (0/1)
            wait_util.go:45: Waiting for full availability of jaeger-operator deployment (0/1)
            wait_util.go:45: Waiting for full availability of jaeger-operator deployment (0/1)
            wait_util.go:45: Waiting for full availability of jaeger-operator deployment (0/1)
            wait_util.go:45: Waiting for full availability of jaeger-operator deployment (0/1)
            wait_util.go:45: Waiting for full availability of jaeger-operator deployment (0/1)
            wait_util.go:45: Waiting for full availability of jaeger-operator deployment (0/1)
            jaeger_test.go:67: timed out waiting for the condition
FAIL
FAIL	github.com/jaegertracing/jaeger-operator/test/e2e	451.394s
make: *** [Makefile:75: e2e-tests] Error 1
```
Test seems to have timed out.

Increased to 2 mins timeout, and it worked fine.

Should we increase the timeout constant, or perhaps add a multiple for this particular test?

**Comment by jpkrohling** [comment] 2019-03-06 14:47
Are you still having this problem? I think I've faced this recently and it was caused by an instance of Jaeger being present when the test was executed. If you still have this problem, could you check the following:

```
$ kubectl get jaegers
$ kubectl get ingresses
```

No Jaegers nor Ingresses should exist.

**Comment by kevinearls** [comment] 2019-03-07 10:55
@jpkrohling Can you assign this to me?  I've seen it also, usually the first time I try to run it.  I assume its some kind of race condition which I run into because I'm running on a slowish machine at the moment.

**Closed** 2019-03-12 13:00 UTC
