### ISSUE TITLE
No support Elasticsearch 8

### ISSUE THREAD

**Issue by konstantin-921** [jaegertracing/jaeger-operator#1801] opened 2022-02-28 16:09 UTC
**Describe the bug**
I updated elasticsearch to v8.0.0.
After that Jaeger operator was broken. And I can't deploy Jaeger operator 1.20.0 again. For some reason the template for the jaeger-span index cannot be created. Before with elasticsearch 7.17.0 everything worked fine. Log:

```
Detected ElasticSearch Version 8
Creating index template jaeger-span
{"error":{"root_cause":[{"type":"parse_exception","reason":"unknown key [template] in the template "}],"type":"parse_exception","reason":"unknown key [template] in the template "},"status":400}
Traceback (most recent call last):
File "/es-rollover/esRollover.py", line 232, in <module>
main()
File "/es-rollover/esRollover.py", line 64, in main
perform_action(action, client, write_alias, read_alias, prefix+'jaeger-span', 'jaeger-span')
File "/es-rollover/esRollover.py", line 79, in perform_action
create_index_template(fix_mapping(mapping, shards, replicas), template_name)
File "/es-rollover/esRollover.py", line 103, in create_index_template
r.raise_for_status()
File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://elk1-fl.domain.com:9200/_template/jaeger-span
```

Jaeger config:

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  strategy: production
  query:
    options:
      query:
        base-path: /jaeger
  collector:
    replicas: 3
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
  storage:
    type: elasticsearch
    options:
      es:
        num-shards: 3
        num-replicas: 0
        server-urls: https://elk1-fl.domain.com:9200
        use-aliases: true
        # create-index-templates: false
        tls:
          ca: /es/certificates/ca.crt
        tags-as-fields:
          all: true
    esRollover:
      conditions: "{\"max_age\": \"1d\"}"
      readTTL: 168h                   
      schedule: "55 23 * * *"
    secretName: jaeger-secret
  volumeMounts:
    - name: certificates
      mountPath: /es/certificates/
      readOnly: true
  volumes:
    - name: certificates
      secret:
        secretName: elkcert
```

**Expected behavior**
Jaeger should be able to create indexes without any problems

**Troubleshoot steps**
I have completely removed all Jaeger elements except for the operator itself and existing secrets. I also checked Elasticsearch to see if there are indexes for Jaeger. There were no such indexes. Then I tried to re-create all the resources for Jaeger through the ```kind: Jaeger``` object, but got the same error.

**Version (please complete the following information):**
 - Jaeger version: Jaeger operator 1.20
 - Deployment: Kubernetes

**Comment by pavolloffay** [comment] 2022-04-05 13:27
Closing as duplicate of https://github.com/jaegertracing/jaeger/issues/3571

**Closed by pavolloffay** 2022-04-05 13:27 UTC
Labels: bug
