### ISSUE TITLE
Upgrading to operator 2.27.1 and Jaeger 1.29.0 will create ES indexes with incorrect replicas

### ISSUE THREAD

**Issue by zzvara** [jaegertracing/jaeger-operator#1723] opened 2022-01-24 13:39 UTC
**Describe the bug**
Jaeger 1.29.0 will create ES indexes with incorrect replicas when using Elasticsearch.

**To Reproduce**

1. Start Jaeger operator.

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger-operator
  namespace: kube-system
spec:
  chart:
    spec:
      chart: jaeger-operator
      sourceRef:
        kind: HelmRepository
        name: jaeger-operator
        namespace: kube-system
      version: 2.27.1
  interval: 30m0s
  values:
    rbac:
      create: true
      clusterRole: true
    resources:
      requests:
        memory: 100Mi
        cpu: 10m
      limits:
        memory: 100Mi
        cpu: 10m
```

2. Deploy Jaeger.

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-default
  namespace: development
spec:
  strategy: production
  ingress:
     enabled: false
  collector:
    maxReplicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 350Mi
      limits:
        cpu: 200m
        memory: 350Mi
  query:
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        cpu: 500m
        memory: 100Mi
  volumeMounts:
    - name: certificates
      mountPath: /es/certificates/
      readOnly: true
  volumes:
    - name: certificates
      secret:
        secretName: elastic-es-http-certs-public
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: https://elastic-es-http.development:9200
        index-prefix: jaeger-development-
        tls:
          ca: /es/certificates/ca.crt
        num-shards: 1
        num-replicas: 0
    secretName: jaeger-default-elastic-credentials
    dependencies:
      enabled: false
      schedule: "55 23 * * *"
      sparkMaster:
      resources:
        requests:
          memory: 4096Mi
        limits:
          memory: 4096Mi
```

**Expected behavior**
Each index that Jaeger creates should have 1 shard and 0 replicas.

**Screenshots**

New indexes are with incorrect replica counts.

<img width="647" alt="image" src="https://user-images.githubusercontent.com/8371789/150793007-9101b535-7cfa-4f72-9ba8-4a122a44a5ae.png">

**Version (please complete the following information):**
 - OS: Flatcar
 - Jaeger version: 1.29.0
 - Deployment: Intel HNS2600TPR Xeon E5

**What troubleshooting steps did you try?**
Checked CRD definition and examples for setting `num-shards`, but could not find any.

**Comment by zzvara** [comment] 2022-01-24 13:43
I added an invalid setting and it then revealed how `es:` attributes are passed.

```
Error: unknown flag: --es.num-whatever
Usage:
  jaeger-query [flags]
  jaeger-query [command]

Available Commands:
  completion  generate the autocompletion script for the specified shell
  docs        Generates documentation
  env         Help about environment variables.
  help        Help about any command
  status      Print the status.
  version     Print the version.

Flags:
      --admin.http.host-port string                           The host:port (e.g. 127.0.0.1:16687 or :16687) for the admin server, including health check, /metrics, etc. (default ":16687")
      --config-file string                                    Configuration file in JSON, TOML, YAML, HCL, or Java properties formats (default none). See spf13/viper for precedence.
      --es-archive.bulk.actions int                           The number of requests that can be enqueued before the bulk processor decides to commit (default 1000)
      --es-archive.bulk.flush-interval duration               A time.Duration after which bulk requests are committed, regardless of other thresholds. Set to zero to disable. By default, this is disabled. (default 200ms)
      --es-archive.bulk.size int                              The number of bytes that the bulk requests can take up before the bulk processor decides to commit (default 5000000)
      --es-archive.bulk.workers int                           The number of workers that are able to receive bulk requests and eventually commit them to Elasticsearch (default 1)
      --es-archive.create-index-templates                     Create index templates at application startup. Set to false when templates are installed manually. (default true)
      --es-archive.enabled                                    Enable extra storage
      --es-archive.index-date-separator string                Optional date separator of Jaeger indices. For example "." creates "jaeger-span-2020.11.20". (default "-")
      --es-archive.index-prefix string                        Optional prefix of Jaeger indices. For example "production" creates "production-jaeger-*".
      --es-archive.index-rollover-frequency-services string   Rotates jaeger-service indices over the given period. For example "day" creates "jaeger-service-yyyy-MM-dd" every day after UTC 12AM. Valid options: [hour, day]. This does not delete old indices. For details on complete index management solutions supported by Jaeger, refer to: https://www.jaegertracing.io/docs/deployment/#elasticsearch-rollover (default "day")
      --es-archive.index-rollover-frequency-spans string      Rotates jaeger-span indices over the given period. For example "day" creates "jaeger-span-yyyy-MM-dd" every day after UTC 12AM. Valid options: [hour, day]. This does not delete old indices. For details on complete index management solutions supported by Jaeger, refer to: https://www.jaegertracing.io/docs/deployment/#elasticsearch-rollover (default "day")
      --es-archive.log-level string                           The Elasticsearch client log-level. Valid levels: [debug, info, error] (default "error")
unknown flag: --es.num-whatever
      --es-archive.max-doc-count int                          The maximum document count to return from an Elasticsearch query. This will also apply to aggregations. (default 10000)
      **--es-archive.num-replicas int                           The number of replicas per index in Elasticsearch (default 1)
      --es-archive.num-shards int                             The number of shards per index in Elasticsearch (default 5)**
      --es-archive.password string                            The password required by Elasticsearch
      --es-archive.remote-read-clusters string                Comma-separated list of Elasticsearch remote cluster names for cross-cluster querying.See Elasticsearch remote clusters and cross-cluster query api.
      --es-archive.send-get-body-as string                    HTTP verb for requests that contain a body [GET, POST].
      --es-archive.server-urls string                         The comma-separated list of Elasticsearch servers, must be full url i.e. http://localhost:9200 (default "http://127.0.0.1:9200")
      --es-archive.sniffer                                    The sniffer config for Elasticsearch; client uses sniffing process to find all nodes automatically, disable if not required
      --es-archive.sniffer-tls-enabled                        Option to enable TLS when sniffing an Elasticsearch Cluster ; client uses sniffing process to find all nodes automatically, disabled by default
      --es-archive.tags-as-fields.all                         (experimental) Store all span and process tags as object fields. If true .tags-as-fields.config-file and .tags-as-fields.include is ignored. Binary tags are always stored as nested objects.
      --es-archive.tags-as-fields.config-file string          (experimental) Optional path to a file containing tag keys which will be stored as object fields. Each key should be on a separate line.  Merged with .tags-as-fields.include
      --es-archive.tags-as-fields.dot-replacement string      (experimental) The character used to replace dots (".") in tag keys stored as object fields. (default "@")
      --es-archive.tags-as-fields.include string              (experimental) Comma delimited list of tag keys which will be stored as object fields. Merged with the contents of .tags-as-fields.config-file
      --es-archive.timeout duration                           Timeout used for queries. A Timeout of zero means no timeout (default 0s)
      --es-archive.tls.ca string                              Path to a TLS CA (Certification Authority) file used to verify the remote server(s) (by default will use the system truststore)
      --es-archive.tls.cert string                            Path to a TLS Certificate file, used to identify this process to the remote server(s)
      --es-archive.tls.enabled                                Enable TLS when talking to the remote server(s)
      --es-archive.tls.key string                             Path to a TLS Private Key file, used to identify this process to the remote server(s)
      --es-archive.tls.server-name string                     Override the TLS server name we expect in the certificate of the remote server(s)
      --es-archive.tls.skip-host-verify                       (insecure) Skip server's certificate chain and host name verification
      --es-archive.token-file string                          Path to a file containing bearer token. This flag also loads CA if it is specified.
      --es-archive.use-aliases                                Use read and write aliases for indices. Use this option with Elasticsearch rollover API. It requires an external component to create aliases before startup and then performing its management. Note that es.max-span-age will influence trace search window start times.
      --es-archive.use-ilm                                    (experimental) Option to enable ILM for jaeger span & service indices. Use this option with  es-archive.use-aliases. It requires an external component to create aliases before startup and then performing its management. ILM policy must be manually created in ES before startup. Supported only for elasticsearch version 7+.
      --es-archive.username string                            The username required by Elasticsearch. The basic authentication also loads CA if it is specified.
      --es-archive.version uint                               The major Elasticsearch version. If not specified, the value will be auto-detected from Elasticsearch.
      --es.bulk.actions int                                   The number of requests that can be enqueued before the bulk processor decides to commit (default 1000)
      --es.bulk.flush-interval duration                       A time.Duration after which bulk requests are committed, regardless of other thresholds. Set to zero to disable. By default, this is disabled. (default 200ms)
      --es.bulk.size int                                      The number of bytes that the bulk requests can take up before the bulk processor decides to commit (default 5000000)
      --es.bulk.workers int                                   The number of workers that are able to receive bulk requests and eventually commit them to Elasticsearch (default 1)
      --es.create-index-templates                             Create index templates at application startup. Set to false when templates are installed manually. (default true)
      --es.index-date-separator string                        Optional date separator of Jaeger indices. For example "." creates "jaeger-span-2020.11.20". (default "-")
      --es.index-prefix string                                Optional prefix of Jaeger indices. For example "production" creates "production-jaeger-*". (default "")
      --es.index-rollover-frequency-services string           Rotates jaeger-service indices over the given period. For example "day" creates "jaeger-service-yyyy-MM-dd" every day after UTC 12AM. Valid options: [hour, day]. This does not delete old indices. For details on complete index management solutions supported by Jaeger, refer to: https://www.jaegertracing.io/docs/deployment/#elasticsearch-rollover (default "day")
      --es.index-rollover-frequency-spans string              Rotates jaeger-span indices over the given period. For example "day" creates "jaeger-span-yyyy-MM-dd" every day after UTC 12AM. Valid options: [hour, day]. This does not delete old indices. For details on complete index management solutions supported by Jaeger, refer to: https://www.jaegertracing.io/docs/deployment/#elasticsearch-rollover (default "day")
      --es.log-level string                                   The Elasticsearch client log-level. Valid levels: [debug, info, error] (default "error")
      --es.max-doc-count int                                  The maximum document count to return from an Elasticsearch query. This will also apply to aggregations. (default 10000)
      --es.max-span-age duration                              The maximum lookback for spans in Elasticsearch (default 72h0m0s)
      --es.num-replicas int                                   The number of replicas per index in Elasticsearch
      --es.num-shards int                                     The number of shards per index in Elasticsearch (default 5)
      --es.password string                                    The password required by Elasticsearch
      --es.remote-read-clusters string                        Comma-separated list of Elasticsearch remote cluster names for cross-cluster querying.See Elasticsearch remote clusters and cross-cluster query api.
      --es.send-get-body-as string                            HTTP verb for requests that contain a body [GET, POST].
      --es.server-urls string                                 The comma-separated list of Elasticsearch servers, must be full url i.e. http://localhost:9200 (default "http://127.0.0.1:9200")
      --es.sniffer                                            The sniffer config for Elasticsearch; client uses sniffing process to find all nodes automatically, disable if not required
      --es.sniffer-tls-enabled                                Option to enable TLS when sniffing an Elasticsearch Cluster ; client uses sniffing process to find all nodes automatically, disabled by default
      --es.tags-as-fields.all                                 (experimental) Store all span and process tags as object fields. If true .tags-as-fields.config-file and .tags-as-fields.include is ignored. Binary tags are always stored as nested objects.
      --es.tags-as-fields.config-file string                  (experimental) Optional path to a file containing tag keys which will be stored as object fields. Each key should be on a separate line.  Merged with .tags-as-fields.include
      --es.tags-as-fields.dot-replacement string              (experimental) The character used to replace dots (".") in tag keys stored as object fields. (default "@")
      --es.tags-as-fields.include string                      (experimental) Comma delimited list of tag keys which will be stored as object fields. Merged with the contents of .tags-as-fields.config-file
      --es.timeout duration                                   Timeout used for queries. A Timeout of zero means no timeout (default 0s)
      --es.tls.ca string                                      Path to a TLS CA (Certification Authority) file used to verify the remote server(s) (by default will use the system truststore)
      --es.tls.cert string                                    Path to a TLS Certificate file, used to identify this process to the remote server(s)
      --es.tls.enabled                                        Enable TLS when talking to the remote server(s)
      --es.tls.key string                                     Path to a TLS Private Key file, used to identify this process to the remote server(s)
      --es.tls.server-name string                             Override the TLS server name we expect in the certificate of the remote server(s)
      --es.tls.skip-host-verify                               (insecure) Skip server's certificate chain and host name verification
      --es.token-file string                                  Path to a file containing bearer token. This flag also loads CA if it is specified.
      --es.use-aliases                                        Use read and write aliases for indices. Use this option with Elasticsearch rollover API. It requires an external component to create aliases before startup and then performing its management. Note that es.max-span-age will influence trace search window start times.
      --es.use-ilm                                            (experimental) Option to enable ILM for jaeger span & service indices. Use this option with  es.use-aliases. It requires an external component to create aliases before startup and then performing its management. ILM policy must be manually created in ES before startup. Supported only for elasticsearch version 7+.
      --es.username string                                    The username required by Elasticsearch. The basic authentication also loads CA if it is specified.
      --es.version uint                                       The major Elasticsearch version. If not specified, the value will be auto-detected from Elasticsearch.
  -h, --help                                                  help for jaeger-query
      --log-level string                                      Minimal allowed log Level. For more levels see https://github.com/uber-go/zap (default "info")
      --metrics-backend string                                Defines which metrics backend to use for metrics reporting: expvar, prometheus, none (default "prometheus")
      --metrics-http-route string                             Defines the route of HTTP endpoint for metrics backends that support scraping (default "/metrics")
      --query.additional-headers strings                      Additional HTTP response headers.  Can be specified multiple times.  Format: "Key: Value" (default [])
      --query.base-path string                                The base path for all HTTP routes, e.g. /jaeger; useful when running behind a reverse proxy (default "/")
      --query.bearer-token-propagation                        Allow propagation of bearer token to be used by storage plugins
      --query.grpc-server.host-port string                    The host:port (e.g. 127.0.0.1:14250 or :14250) of the query's gRPC server (default ":16685")
      --query.grpc.tls.cert string                            Path to a TLS Certificate file, used to identify this server to clients
      --query.grpc.tls.client-ca string                       Path to a TLS CA (Certification Authority) file used to verify certificates presented by clients (if unset, all clients are permitted)
      --query.grpc.tls.enabled                                Enable TLS on the server
      --query.grpc.tls.key string                             Path to a TLS Private Key file, used to identify this server to clients
      --query.http-server.host-port string                    The host:port (e.g. 127.0.0.1:14268 or :14268) of the query's HTTP server (default ":16686")
      --query.http.tls.cert string                            Path to a TLS Certificate file, used to identify this server to clients
      --query.http.tls.client-ca string                       Path to a TLS CA (Certification Authority) file used to verify certificates presented by clients (if unset, all clients are permitted)
      --query.http.tls.enabled                                Enable TLS on the server
      --query.http.tls.key string                             Path to a TLS Private Key file, used to identify this server to clients
      --query.max-clock-skew-adjustment duration              The maximum delta by which span timestamps may be adjusted in the UI due to clock skew; set to 0s to disable clock skew adjustments (default 0s)
      --query.static-files string                             The directory path override for the static assets for the UI
      --query.ui-config string                                The path to the UI configuration file in JSON format
      --span-storage.type string                              (deprecated) please use SPAN_STORAGE_TYPE environment variable. Run this binary with the 'env' command for help.

```

**Comment by zzvara** [comment] 2022-01-27 13:56
Actually, there could be some bug or incompatibility with ES 7.16.1, because 1 replica is created anyway:

![image](https://user-images.githubusercontent.com/8371789/151372681-4681b48d-6e82-4e8d-bf55-69733ea2ebee.png)

![image](https://user-images.githubusercontent.com/8371789/151372760-2e661d1d-8ba2-4b50-b605-6aa0f24a0c20.png)

![image](https://user-images.githubusercontent.com/8371789/151372802-aa259792-d0c6-4241-9e54-0ab576850e08.png)

**Comment by rubenvp8510** [comment] 2022-02-21 16:36
@pavolloffay @kevinearls Could you take a look please?

**Comment by kevinearls** [comment] 2022-03-07 12:27
@zzvara I was not able to reproduce your problem with the number of replicas.  If I specified 0 I got 0.  I was able to reproduce the "all shards failed" error.

However, this can be easily fixed by dropping the trailing "-" on your index-prefix.

**Comment by pavolloffay** [comment] 2022-03-07 13:05
Closing per @kevinearls comment.

**Closed by pavolloffay** 2022-03-07 13:05 UTC
Labels: bug, Elasticsearch
